# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Zachary Bennett
email: bennett.zachary@outlook.com
description: > # this means to ignore newlines until "baseurl:"
  Passion for people. Passion for code.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
twitter_username: z_bennett_
github_username:  zbennett10
linkedin_username: zbennett10
pluralsight_username: zachary-bennett

# Build settings
markdown: kramdown
theme: minima
